/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  // Inserts seed entries
  await knex('item').insert([
    {
      id: 1,
      wishlist_id: 1,
      item: 'Nintendo Switch',
      priority: 'High',
      price: 299,
      purchased: false,
      image_url: null,
    },
    {
      id: 2,
      wishlist_id: 1,
      item: 'AirPods Pro',
      priority: 'Medium',
      price: 249,
      purchased: false,
      image_url: null,
    },
    {
      id: 3,
      wishlist_id: 2,
      item: 'Apple Watch Series 6',
      priority: 'High',
      price: 399,
      purchased: false,
      image_url: null,
    },
    {
      id: 4,
      wishlist_id: 2,
      item: 'AirPods Pro',
      priority: 'Medium',
      price: 249,
      purchased: false,
      image_url: null,
    },
    {
      id: 5,
      wishlist_id: 3,
      item: 'Nintendo Switch',
      priority: 'High',
      price: 299,
      purchased: false,
      image_url: null,
    },
    {
      id: 6,
      wishlist_id: 3,
      item: 'AirPods Pro',
      priority: 'Medium',
      price: 249,
      purchased: false,
      image_url: null,
    },
    {
      id: 7,
      wishlist_id: 4,
      item: 'Apple Watch Series 6',
      priority: 'High',
      price: 399,
      purchased: false,
      image_url: null,
    },
    {
      id: 8,
      wishlist_id: 4,
      item: 'AirPods Pro',
      priority: 'Medium',
      price: 249,
      purchased: false,
      image_url: null,
    },
    {
      id: 9,
      wishlist_id: 5,
      item: 'Nintendo Switch',
      priority: 'High',
      price: 299,
      purchased: false,
      image_url: null,
    },
    {
      id: 10,
      wishlist_id: 5,
      item: 'AirPods Pro',
      priority: 'Medium',
      price: 249,
      purchased: false,
      image_url: null,
    },
    {
      id: 11,
      wishlist_id: 6,
      item: "Baldur's Gate 3",
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 12,
      wishlist_id: 6,
      item: 'Cyberpunk 2077',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 13,
      wishlist_id: 7,
      item: 'Mario Party',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 14,
      wishlist_id: 7,
      item: 'Super Smash Bros. Ultimate',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 15,
      wishlist_id: 8,
      item: 'The Legend of Zelda: Breath of the Wild',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 16,
      wishlist_id: 8,
      item: 'Super Mario Odyssey',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 17,
      wishlist_id: 9,
      item: '3D Printing Filament',
      priority: 'High',
      price: 19.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 18,
      wishlist_id: 9,
      item: '3D Printer',
      priority: 'Medium',
      price: 299.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 19,
      wishlist_id: 10,
      item: 'Pusheen Plush',
      priority: 'High',
      price: 19.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 20,
      wishlist_id: 10,
      item: 'Pusheen Mug',
      priority: 'Medium',
      price: 14.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 21,
      wishlist_id: 11,
      item: 'Magic: The Gathering Zendikar Rising Set Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 22,
      wishlist_id: 11,
      item: 'Magic: The Gathering Zendikar Rising Collector Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 23,
      wishlist_id: 12,
      item: 'Magic: The Gathering Adventures in the Forgotten Realms Set Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 24,
      wishlist_id: 12,
      item: 'Magic: The Gathering Adventures in the Forgotten Realms Collector Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 25,
      wishlist_id: 13,
      item: 'Magic: The Gathering Strixhaven Set Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 26,
      wishlist_id: 13,
      item: 'Magic: The Gathering Strixhaven Collector Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 27,
      wishlist_id: 14,
      item: 'Magic: The Gathering Kaldheim Set Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 28,
      wishlist_id: 14,
      item: 'Magic: The Gathering Kaldheim Collector Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 29,
      wishlist_id: 15,
      item: 'Magic: The Gathering Commander Legends Draft Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 30,
      wishlist_id: 15,
      item: 'Magic: The Gathering Commander Legends Collector Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 31,
      wishlist_id: 16,
      item: 'Magic: The Gathering Double Masters VIP Edition',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 32,
      wishlist_id: 16,
      item: 'Magic: The Gathering Double Masters Booster Box',
      priority: 'Medium',
      price: 249.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 33,
      wishlist_id: 17,
      item: 'Magic: The Gathering Core Set 2021 Collector Booster Box',
      priority: 'High',
      price: 99.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 34,
      wishlist_id: 17,
      item: 'Star Wars: The Mandalorian The Child Animatronic Edition',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 35,
      wishlist_id: 18,
      item: 'One Piece: Pirate Warriors 4',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 36,
      wishlist_id: 18,
      item: 'Dragon Ball Z: Kakarot',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 37,
      wishlist_id: 19,
      item: 'The Lord of the Rings: The Motion Picture Trilogy',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 38,
      wishlist_id: 19,
      item: 'Pulp Fiction',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 39,
      wishlist_id: 20,
      item: 'The Sandman: The Deluxe Edition Book One',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 40,
      wishlist_id: 20,
      item: 'The Sandman: The Deluxe Edition Book Two',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 41,
      wishlist_id: 21,
      item: 'The Sandman Omnibus Vol. 1',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 42,
      wishlist_id: 21,
      item: 'The Sandman Omnibus Vol. 2',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 43,
      wishlist_id: 22,
      item: 'The Sandman Omnibus Vol. 3',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 44,
      wishlist_id: 22,
      item: 'Promethea Book One',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 45,
      wishlist_id: 23,
      item: 'Promethea Book Two',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 46,
      wishlist_id: 23,
      item: 'Promethea Book Three',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 47,
      wishlist_id: 24,
      item: 'Promethea Book Four',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 48,
      wishlist_id: 24,
      item: 'Promethea Book Five',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 49,
      wishlist_id: 25,
      item: 'The Invisibles Book One Deluxe Edition',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 50,
      wishlist_id: 25,
      item: 'The Invisibles Book Two Deluxe Edition',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 51,
      wishlist_id: 26,
      item: 'The Invisibles Book Three Deluxe Edition',
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 52,
      wishlist_id: 26,
      item: 'The Invisibles Book Four Deluxe Edition',
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 53,
      wishlist_id: 27,
      item: "Maus: A Survivor's Tale",
      priority: 'High',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 54,
      wishlist_id: 27,
      item: "Maus II: A Survivor's Tale: And Here My Troubles Began",
      priority: 'Medium',
      price: 59.99,
      purchased: false,
      image_url: null,
    },
    {
      id: 55,
      wishlist_id: 28,
      item: 'MacBook Pro',
      priority: 'High',
      price: 1299,
      purchased: false,
      image_url: null,
    },
    {
      id: 56,
      wishlist_id: 28,
      item: 'MacBook Air',
      priority: 'Medium',
      price: 999,
      purchased: false,
      image_url: null,
    },
    {
      id: 57,
      wishlist_id: 29,
      item: 'Nvidia GeForce RTX 3080',
      priority: 'High',
      price: 699,
      purchased: false,
      image_url: null,
    },
    {
      id: 58,
      wishlist_id: 29,
      item: 'Nvidia GeForce RTX 3070',
      priority: 'Medium',
      price: 499,
      purchased: false,
      image_url: null,
    },
    {
      id: 59,
      wishlist_id: 30,
      item: 'AMD Ryzen 9 5950X',
      priority: 'High',
      price: 799,
      purchased: false,
      image_url: null,
    },
    {
      id: 60,
      wishlist_id: 30,
      item: 'AMD Ryzen 9 5900X',
      priority: 'Medium',
      price: 549,
      purchased: false,
      image_url: null,
    },
    {
      id: 61,
      wishlist_id: 31,
      item: 'AMD Ryzen 7 5800X',
      priority: 'High',
      price: 449,
      purchased: false,
      image_url: null,
    },
    {
      id: 62,
      wishlist_id: 31,
      item: 'AMD Ryzen 5 5600X',
      priority: 'Medium',
      price: 299,
      purchased: false,
      image_url: null,
    },
    {
      id: 63,
      wishlist_id: 32,
      item: 'AMD Radeon RX 6900 XT',
      priority: 'High',
      price: 999,
      purchased: false,
      image_url: null,
    },
    {
      id: 64,
      wishlist_id: 32,
      item: 'My Little Pony',
      priority: 'Medium',
      price: 99,
      purchased: false,
      image_url: null,
    },
    {
      id: 65,
      wishlist_id: 33,
      item: 'Desk',
      priority: 'High',
      price: 199,
      purchased: false,
      image_url: null,
    },
    {
      id: 66,
      wishlist_id: 33,
      item: 'Chair',
      priority: 'Medium',
      price: 99,
      purchased: false,
      image_url: null,
    },
  ])
}
